# Generated by Django 5.2 on 2025-05-11 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_default_roles'),
        ('core', '0003_user_groups_user_user_permissions_and_more'),
    ]

    operations = [
    ]
